version: '3.8'

services:
  anpta:
    build:
      context: .
      dockerfile: anpta/Dockerfile
    image: anpta:latest
    container_name: anpta
    volumes:
     - .:/data/
    command: /bin/bash
    tty: true
    stdin_open: true
